global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'crowdsec'
    static_configs:
      - targets: ['crowdsec:6060']

  - job_name: 'authelia'
    metrics_path: /api/metrics
    static_configs:
      - targets: ['authelia:9091']
